Feature/sv 65 list tras
LBHackney-IT/mat-service pull request #34
Opened 2020-08-20 14:49 UTC by LBHTKarki

# What?
Adds the "List TRAs" page for SV-65. Some of the wip changes have already been merged in the previous PR "Add base gateway for tickets SV-65 and SV-107" that enabled us to use the new db gateway. Especially the page should be looked at separately to ensure it's implemented correctly.
 
I have re-created the tra related tables from scratch to save time, so the migrations assume we start with the empty database. Moving forward proper migration process will be followed but for now it's a lot faster to just start again. The previous merged migrations were wip versions so shouldn't really have been merged, but since we don't have the db on staging yet this approach will work fine for now.

# Why?
Enables officers to view TRAs on their patch

# Checklist

- [x ] Unit tests
- [ ] Integration tests
- [ x] Cypress tests

# Notes
I've included seeds.sql file so local db can be quickly populated with valid TRA related values.

Initially I added foreign key constraints to the tables, but because we need to migrate existing data over with PK values from other systems, it became a bit awkward to manage, especially when using fresh seed data for testing. This is relatively static data, so data integrity shouldn't become an issue at any point.

# Next steps

- Add integration tests for postgresql once we have agreed on a common approach on what should be tested and how
- Discuss whether interfaces should be used when handling data received from postgres
- Currently the patchid used by the page is hard coded, but once we know how we handle logged in users i.e. get their details app wide, we can update this so we get the officer's patch from CRM and then get the TRAs for that particular patch.

2020-09-02 08:40 UTC, LBHTKarki commented on next.config.js
> +    webpack: (config, { webpack }) => {
I couldn't get the project to build without disabling the plugin. There seems to be a conflict between the pg-promise and this one, and this seems like a clean way to resolve it since this plugin is not required for the project.

2020-09-03 10:29 UTC, bjpirt requested changes

2020-09-03 10:29 UTC, bjpirt commented on src/gateways/matPostgresGateway.ts
> -        connectionString: process.env.TEST_DATABASE_URL //TODO: update this to prod value
I'm confused why we need to do this separately - can't we just set DATABASE_URL differently when in the test environment?

2020-09-03 13:53 UTC, LBHTKarki commented on src/gateways/matPostgresGateway.ts
> -        connectionString: process.env.TEST_DATABASE_URL //TODO: update this to prod value
I've simplified the config and also added the DATABASE_URL to the serverless.yml. The db connection implementation requires some refactoring but hopefully the config at least makes more sense now.

2020-09-03 13:55 UTC, LBHTKarki commented on src/gateways/matPostgresGateway.ts
> +      WHERE TRAPatchAssociation.PatchCRMId ='${patchId}'
Good point, I've updated the query. I had to keep it as a one liner as I couldn't get the formatted version (wrapped in ``) to work.

2020-09-03 15:38 UTC, bjpirt approved these changes

2020-09-03 15:38 UTC, bjpirt commented on src/mappings/apiTRAToUiTRA.ts
> +    const mappedTRAs: TRA[] = [];
Minor comment - this is a perfect use case for array.map which would simplify the code a lot
```
return tras.map(tra => ({
    id: tra.traid,
    name: tra.name,
    patchid: tra.patchcrmid
})
```

2020-09-04 08:21 UTC, ccp92 approved these changes
lgtm

2020-09-04 08:32 UTC, merged